# Site settings
title: Joel Ferrier
email: jferrier45@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Devops Shenanigans
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://joelferrier.com" # the base hostname & protocol for your site
github_username:  joelferrier

# Build settings
markdown: redcarpet
